### ISSUE TITLE
Can't determine row being drawn

### ISSUE THREAD

**Issue by swelshh** [vegarringdal/wakanda_widgets#2]
Hey Vegar,

I'm binding an array to the grid, and I can't seem to determine the row that is being drawn in the "cellDrawn" event or find out anything about the datasource.  It looks like your examples are based on server datasources where you can access event.data.data.  But when I bind an array event.data.data is always null.  Is there a way to find out about the array element for the row that is being drawn?

**Comment by vegarringdal** [comment]
Not at the computer atm, we used event.data.attribute and event.data.entity in checkbox celldraw so they should be populated, first draw and empty rows the event.data.entity will prb be null...

**Comment by swelshh** [comment]
Oh sorry, you're right, I was looking at the event for empty rows!
